name:                saffire-mixer
version:             0.1.0.0
github:              "githubuser/saffire-mixer"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/saffire-mixer#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- universum
- fmt
- memory
- mtl
- enumerate
- aeson
- aeson-pretty
- yaml
- data-default
- lens
- split
- text
- generic-deriving
- optparse-applicative


default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables
- DeriveAnyClass
- DeriveGeneric
- DuplicateRecordFields
- LambdaCase
- ViewPatterns

library:
  source-dirs: src

executables:
  saffire-mixer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    frameworks:
     - FWAUserLib
    dependencies:
    - saffire-mixer

tests:
  saffire-mixer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - saffire-mixer
